[package]
authors = ["Alex Martens <alexmgit@protonmail.com>"]
name = "testsuite-peer"
publish = false
edition = "2018"
version = "0.1.0"

[dependencies]
tokio = {version = "^1", features = ["full"]}
reqwest = "~0.11"
testsuite-assets = { path = "../testsuite-assets" }
