[package]
authors = ["Alex Martens <alex@thinglab.org>"]
name = "testsuite-peer"
publish = false
edition = "2018"
version = "0.1.0"

[dependencies]
isahc = "1.5"
testsuite-assets = { path = "../testsuite-assets" }
